### ISSUE TITLE
Integrate grassroots map into NY dhamma site

### ISSUE THREAD

**Issue by nwshane** [NY-Vipassana-Association/grassroots-map#2]
Barry (an assistant teacher from this region) has approved the grassroots map for public use, so we now need to figure out how to integrate it into the [NY dhamma site](https://www.ny.us.dhamma.org/).

*Jeremy Frey-Wedeen 9/29/18*: I propose that we have a whole page on the website dedicated to "Your local community" with the map as the main feature of the page.

*Jeremy FW 10/9/18*: Would it be possible to create a separate tab on the new student section of the website saying, connect with your local community? For this to work, we'd need to password block the group sitting links. Otherwise, all the information on the map should be fine for new students to see (perhaps even inspiring). In terms of extra content on the page, I think the map should be the center piece of the page, but that there should be a little blurb about what the Grassroots Project is about, and the various features of the map.

Remaining questions:
1. Should the grassroots map take up the full screen, like [it does now](https://vipassana-grassroots-map.surge.sh/)? Or do we prefer to put it inside of a box within the context of the overall site? One possibility: we could show a minimized version of the map within an iFrame (in a box), and when users click on the map, it would take them to the full website.
2. What text / links do we want available on the map itself?
3. What URL should the map live at?

**Comment by jfw305** [comment]
Question feedback:

1. I think we should make it the major feature of the page- big enough so that it can be used easily- but not the full page. I think it would be best if the user could use the map directly on the NYVA page itself. Does that answer question 3?
2. I think the map currently has all the links and texts it needs (although please feel free to contribute more ideas). The one thing I think it's missing at this point is a link within the group sitting icon text boxes that takes people to some sort of 3rd party??? platform where they can sign up to join the group sit directly on the page itself. It would also be nice if that 3rd party platform, had multiple administrative back-end layers to it where 1. the group sit hosts could manage the dates and times they make available for people to sign up (ideally there are automatic reminder emails and other useful add ons built into the system) and 2. another administrative layer that is monitored by the Community Planning Committee which would be able to track all group sitting in the region and get a sense of overall engagement per sitting. Is that possible?

Here is a draft proposal for the text content that we could use for the "Your Local Community Webpage":  https://drive.google.com/open?id=1mYZgYvanKUUsvIK_3XWXPAAdHdHigMxyeRS-YUo0LiE 

To start setting this up on the website, please communicate with Kyle Garrity and Diego Perez from the Communications Committee (garritron@gmail.com , dperezlacera@gmail.com), and Yale Spector and Nyan Win from the Tech Committee. Together you should be able to get something up :)

Thank you!

**Comment by nwshane** [comment]
@jfw305 Thanks for all that useful info! A few follow up questions before I write to the communications and tech committees:

1. Is it okay if we leave the group sitting 3rd party platform integration for a subsequent release? That seems like a large project, and I'm guessing it would push back the initial release of this map significantly. For now, is it alright if we manually update the group sittings, and simply provide contact info for meditators to get in touch with the hosts?
2. I agree with you, I think it'd be nice to have the map be usable directly on the new community page. I also think it'd be nice if users had the option to open it up in a separate tab, so that the map takes up the full browser and is easier to view/navigate. Does that sound okay to you? We can add a link (either with text or an icon) above / below the map that would open it up in a separate tab. 
3. Can we use the text "Local Community" for the tab for this new page, or even just "Community"? "Your Local Community" seems like it'd take a lot of space in an already crammed navigation bar.

**Comment by jfw305** [comment]
Hi Nathan,

Thanks for your feedback. Here is a quick summary of mine:

1. Let's get started with a simple third party platform and then develop this is in a more focused way over time. Even the third party platform option shouldn't delay our release of the website. The site is still useful with just the contact info. Plus, it will take time to train the hosts on managing the third party platform.

2. Yes sounds good! Lets embed the map into the page and have a link where people can open it up to full size.

3. Let's go with Local Communities"
